FROM python:3.10-slim

RUN pip install pipenv

ARG MANGA_URL
ARG CHAPTER_NUMBER
ARG NOTIFICATION_FROM_EMAIL
ARG NOTIFICATION_TO_EMAIL
ARG SMTP_SERVER
ARG SMTP_PORT
ARG SMTP_USERNAME
ARG SMTP_PASSWORD

ENV MANGA_URL=${MANGA_URL}
ENV CHAPTER_NUMBE=${CHAPTER_NUMBER}
ENV NOTIFICATION_FROM_EMAIL=${NOTIFICATION_FROM_EMAIL}
ENV NOTIFICATION_TO_EMAIL=${NOTIFICATION_TO_EMAIL}
ENV SMTP_SERVER=${SMTP_SERVER}
ENV SMTP_PORT=${SMTP_PORT}
ENV SMTP_USERNAME=${SMTP_USERNAME}
ENV SMTP_PASSWORD=${SMTP_PASSWORD}

WORKDIR /app

COPY . .

RUN pipenv install --deploy --system

CMD ["python", "main.py"]